version: "3"

tasks:
  # --- Core Development ---
  fmt:
    desc: "Format all Rust code"
    cmds:
      - cargo fmt

  build:
    desc: "Build in debug mode"
    deps: [fmt]
    cmds:
      - cargo build

  build:release:
    desc: "Build optimized release binary"
    deps: [check:all]
    cmds:
      - cargo build --release

  check:
    desc: "Run fmt, cargo check, and clippy"
    deps: [fmt]
    cmds:
      - cargo check
      - cargo clippy -- -D warnings

  test:
    desc: "Run all tests"
    cmds:
      - cargo test

  test:verbose:
    desc: "Run tests with output visible (--nocapture)"
    cmds:
      - cargo test -- --nocapture

  check:all:
    desc: "Run fmt, clippy, and tests"
    cmds:
      - task: fmt
      - task: check
      - task: test

  # --- Run ---
  run:
    desc: "Run melos-rs (pass args after --)"
    deps: [build]
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  run:list:
    desc: "List all packages in the workspace"
    cmds:
      - cargo run -- list

  run:list:long:
    desc: "List packages with full details"
    cmds:
      - cargo run -- list --long

  run:bootstrap:
    desc: "Bootstrap all packages (pub get)"
    cmds:
      - cargo run -- bootstrap

  run:clean:
    desc: "Clean all Flutter packages"
    cmds:
      - cargo run -- clean

  run:exec:
    desc: "Exec a command in packages (pass args after --)"
    cmds:
      - cargo run -- exec {{.CLI_ARGS}}

  run:version:
    desc: "Run version command (pass args after --)"
    cmds:
      - cargo run -- version {{.CLI_ARGS}}

  # --- Install ---
  install:
    desc: "Install melos-rs binary to ~/.cargo/bin"
    deps: [check:all]
    cmds:
      - cargo install --path .

  # --- Versioning ---
  version:patch:
    desc: "Bump patch version (0.4.2 -> 0.4.3)"
    cmds:
      - |
        set -e
        CURRENT=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
        NEXT="$MAJOR.$MINOR.$((PATCH + 1))"
        sed -i "s/^version = \"$CURRENT\"/version = \"$NEXT\"/" Cargo.toml
        cargo generate-lockfile
        echo "Bumped $CURRENT -> $NEXT"

  version:minor:
    desc: "Bump minor version (0.4.2 -> 0.5.0)"
    cmds:
      - |
        set -e
        CURRENT=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
        NEXT="$MAJOR.$((MINOR + 1)).0"
        sed -i "s/^version = \"$CURRENT\"/version = \"$NEXT\"/" Cargo.toml
        cargo generate-lockfile
        echo "Bumped $CURRENT -> $NEXT"

  version:major:
    desc: "Bump major version (0.4.2 -> 1.0.0)"
    cmds:
      - |
        set -e
        CURRENT=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
        NEXT="$((MAJOR + 1)).0.0"
        sed -i "s/^version = \"$CURRENT\"/version = \"$NEXT\"/" Cargo.toml
        cargo generate-lockfile
        echo "Bumped $CURRENT -> $NEXT"

  version:tag:
    desc: "Git tag current version as v<version>"
    cmds:
      - |
        set -e
        VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')
        git tag "v$VERSION"
        echo "Tagged v$VERSION"

  # --- Code Quality ---
  loc:
    desc: "Show lines of code statistics using tokei"
    cmds:
      - tokei

  clean:
    desc: "Remove build artifacts"
    cmds:
      - cargo clean

  # --- Benchmark: melos vs melos-rs ---
  bench:setup:
    desc: "Generate test Flutter monorepo for benchmarks (15 packages)"
    status:
      - test -f test-flutter-repo/melos.yaml
    cmds:
      - |
        set -e
        ROOT="test-flutter-repo"
        rm -rf "$ROOT"
        mkdir -p "$ROOT/packages"

        # --- Root melos.yaml (for melos-rs 6.x compat) ---
        cat > "$ROOT/melos.yaml" <<'YAML'
        name: bench_workspace
        packages:
          - packages/**
        YAML

        # --- Root pubspec.yaml (for melos 7.x) ---
        cat > "$ROOT/pubspec.yaml" <<'YAML'
        name: bench_workspace
        publish_to: none
        environment:
          sdk: ^3.11.0
        workspace:
          - packages/analytics
          - packages/api
          - packages/app
          - packages/auth
          - packages/config
          - packages/core
          - packages/dashboard
          - packages/features
          - packages/logger
          - packages/navigation
          - packages/testing
          - packages/theme
          - packages/ui
          - packages/utils
          - packages/widgets
        dev_dependencies:
          melos: ^7.0.0
        melos:
          name: bench_workspace
        YAML

        # Helper: create a Dart package
        # Usage: mk_dart <name> <version> [deps...]
        mk_dart() {
          local name="$1" version="$2"; shift 2
          local dir="$ROOT/packages/$name"
          mkdir -p "$dir/lib/src"
          echo "// $name library" > "$dir/lib/$name.dart"
          echo "// internal" > "$dir/lib/src/impl.dart"
          {
            echo "name: $name"
            echo "version: $version"
            echo "resolution: workspace"
            echo "environment:"
            echo "  sdk: ^3.5.0"
            if [ $# -gt 0 ]; then
              echo "dependencies:"
              for dep in "$@"; do
                echo "  $dep: any"
              done
            fi
          } > "$dir/pubspec.yaml"
        }

        # Helper: create a Flutter package
        # Usage: mk_flutter <name> <version> [deps...]
        mk_flutter() {
          local name="$1" version="$2"; shift 2
          local dir="$ROOT/packages/$name"
          mkdir -p "$dir/lib/src"
          echo "// $name Flutter library" > "$dir/lib/$name.dart"
          echo "// internal" > "$dir/lib/src/impl.dart"
          {
            echo "name: $name"
            echo "version: $version"
            echo "resolution: workspace"
            echo "environment:"
            echo "  sdk: ^3.5.0"
            echo "dependencies:"
            echo "  flutter:"
            echo "    sdk: flutter"
            for dep in "$@"; do
              echo "  $dep: any"
            done
            echo "flutter:"
            echo "  uses-material-design: true"
          } > "$dir/pubspec.yaml"
        }

        # --- 5 pure Dart packages ---
        mk_dart  core       "1.0.0"
        mk_dart  utils      "1.2.0"   core
        mk_dart  logger     "0.5.0"   core
        mk_dart  config     "2.0.0"   core utils
        mk_dart  auth       "1.1.0"   core logger config

        # --- 5 Flutter packages ---
        mk_flutter app        "3.0.0"  core auth
        mk_flutter ui         "1.0.0"
        mk_flutter widgets    "1.3.0"  ui
        mk_flutter navigation "0.8.0"  ui widgets
        mk_flutter theme      "1.0.0"  ui

        # --- 5 mixed packages with interdependencies ---
        mk_dart    api        "2.0.0"  core config auth
        mk_flutter features   "1.5.0"  ui widgets api
        mk_dart    analytics  "0.3.0"  core logger
        mk_flutter dashboard  "1.0.0"  features analytics theme
        mk_dart    testing    "0.1.0"  core utils

        # --- Install melos as dev dependency for 7.x ---
        cd "$ROOT" && dart pub get && cd ..

        echo ""
        echo "Created 15 packages in $ROOT/packages/"
        ls "$ROOT/packages/"

  bench:list:
    desc: "Benchmark: melos list vs melos-rs list"
    dir: test-flutter-repo
    deps: [bench:setup, build:release]
    cmds:
      - |
        hyperfine \
          --warmup 3 \
          --min-runs 20 \
          --export-markdown ../bench-list.md \
          --command-name 'melos list' \
          'melos list' \
          --command-name 'melos-rs list' \
          '../target/release/melos-rs list'

  bench:list:json:
    desc: "Benchmark: melos list --json vs melos-rs list --json"
    dir: test-flutter-repo
    deps: [bench:setup, build:release]
    cmds:
      - |
        hyperfine \
          --warmup 3 \
          --min-runs 20 \
          --export-markdown ../bench-list-json.md \
          --command-name 'melos list --json' \
          'melos list --json' \
          --command-name 'melos-rs list --json' \
          '../target/release/melos-rs list --json'

  bench:exec:
    desc: "Benchmark: melos exec -- echo hi vs melos-rs exec -- echo hi"
    dir: test-flutter-repo
    deps: [bench:setup, build:release]
    cmds:
      - |
        hyperfine \
          --warmup 3 \
          --min-runs 10 \
          --export-markdown ../bench-exec.md \
          --command-name 'melos exec -- echo hi' \
          'melos exec -- echo hi' \
          --command-name 'melos-rs exec -- echo hi' \
          '../target/release/melos-rs exec -- echo hi'

  bench:bootstrap:
    desc: "Benchmark: melos bootstrap vs melos-rs bootstrap (network-bound)"
    dir: test-flutter-repo
    deps: [bench:setup, build:release]
    cmds:
      - |
        hyperfine \
          --warmup 1 \
          --min-runs 3 \
          --export-markdown ../bench-bootstrap.md \
          --command-name 'melos bootstrap' \
          'melos bootstrap' \
          --command-name 'melos-rs bootstrap' \
          '../target/release/melos-rs bootstrap'

  bench:all:
    desc: "Run all benchmarks (list, list --json, exec)"
    cmds:
      - task: bench:list
      - task: bench:list:json
      - task: bench:exec
      # NOTE: bench:bootstrap skipped — melos-rs generates pubspec_overrides.yaml
      # which conflicts with Dart 3.11 workspace resolution: workspace.
      # Run bench:bootstrap separately on a non-workspace test repo if needed.
      - echo ""
      - echo "=== Benchmark results saved to bench-*.md ==="

  bench:clean:
    desc: "Remove test Flutter repo and benchmark results"
    cmds:
      - rm -rf test-flutter-repo
      - rm -f bench-list.md bench-list-json.md bench-exec.md bench-bootstrap.md
